namespace backend.Interfaces;

/// <summary>
/// AI provider for generating smart recipe suggestions.
/// </summary>
public interface ISmartRecipeAIProvider
{
    /// <summary>
    /// Generate recipe suggestions based on user context.
    /// </summary>
    Task<SmartRecipeAIResponse> GenerateRecipesAsync(
        SmartRecipeAIRequest request,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Generate a single recipe based on context.
    /// Used for streaming - generates one recipe at a time.
    /// </summary>
    /// <param name="request">The recipe generation request context.</param>
    /// <param name="recipeIndex">Index of this recipe in the generation sequence (0-based).</param>
    /// <param name="previousTitles">Titles of previously generated recipes to avoid duplicates.</param>
    /// <param name="missingTarget">Target for missing ingredients: "zero" or "one-to-two".</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    Task<SmartRecipeAIResponse> GenerateSingleRecipeAsync(
        SmartRecipeAIRequest request,
        int recipeIndex,
        IReadOnlyList<string> previousTitles,
        string missingTarget,
        CancellationToken cancellationToken = default);
}

/// <summary>
/// Request payload for AI recipe generation.
/// </summary>
public record SmartRecipeAIRequest(
    IReadOnlyList<string> InventoryItems,
    int ServingsCount,
    IReadOnlyList<string> Preferences,
    IReadOnlyList<string> Avoid,
    IReadOnlyList<SmartRecipeReference> ReferenceRecipes);

/// <summary>
/// Reference recipe from database for AI context.
/// </summary>
public record SmartRecipeReference(
    string Title,
    string? Description,
    IReadOnlyList<string> Ingredients,
    IReadOnlyList<string> Tags);

/// <summary>
/// AI response with generated recipes.
/// </summary>
public record SmartRecipeAIResponse(
    bool Success,
    IReadOnlyList<GeneratedRecipe>? Recipes = null,
    string? ErrorMessage = null);

/// <summary>
/// A recipe generated by AI.
/// </summary>
public record GeneratedRecipe(
    string Title,
    string Description,
    decimal Servings,
    int TotalTimeMinutes,
    string Difficulty,
    IReadOnlyList<GeneratedIngredient> Ingredients,
    IReadOnlyList<GeneratedStep> Steps,
    IReadOnlyList<string> MissingIngredients,
    decimal MatchScore,
    // Nutrition estimates from AI
    decimal? Calories = null,
    decimal? Carbohydrates = null,
    decimal? Fat = null,
    decimal? Protein = null,
    decimal? Sugar = null,
    decimal? Sodium = null,
    decimal? SaturatedFat = null);

public record GeneratedIngredient(
    string Name,
    decimal Amount,
    string Unit,
    string? Category = null);

public record GeneratedStep(
    int Order,
    string Instruction,
    int? SuggestedSeconds = null);
